spring.application.name=job-search-app

jobicy.api.base-url=https://jobicy.com
linkedin.api.base-url=https://www.linkedin.com

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/job-search-app}

spring.data.redis.url=${REDIS_URL:redis://localhost:6379}

spring.cache.type=redis
spring.cache.redis.time-to-live=${CACHE_TTL:10m}